export const siteConfig = {
  name: "LLMSlim",
  shortName: "LLMSlim",
  domain: "www.llmslim.app",
  url: "https://www.llmslim.app",
  ogImage: "https://www.llmslim.app/llmslim_brand_id.png",
  logo: "https://www.llmslim.app/llmslim_logo.png",
  favicon: "https://www.llmslim.app/favicon.png",
  title: "LLMSlim — Adaptive Context Planning for LLM Applications",
  description: "Open-source, provider-neutral Python library for deterministic context planning and provenance-aware compression.",
  author: "Yashvardhan Thanvi",
  creator: "Yashvardhan Thanvi",
  publisher: "LLMSlim Core Team",
  category: "Developer Tools & AI Infrastructure",
  version: "0.6.0",
  github: "https://github.com/Thanatos9404/llmslim",
  linkedin: "https://www.linkedin.com/in/yashvardhan-thanvi-2a3a661a8/",
  pypi: "https://pypi.org/project/llmslim/",
  productHunt: "https://www.producthunt.com/products/llmslim",
  license: "https://opensource.org/licenses/MIT",
  keywords: [
    "prompt compression",
    "LLM context compression",
    "adaptive context planner",
    "provenance-aware prioritization",
    "RAG context compression",
    "Python AI infrastructure",
    "TF-IDF context compressor",
    "LexRank sentence scoring",
  ],
  googleSiteVerification: "google372537cef67c55b3",
};
