export const siteConfig = {
  name: "LLMSlim",
  shortName: "LLMSlim",
  domain: "llmslim.app",
  url: "https://llmslim.app",
  ogImage: "https://llmslim.app/llmslim_brand_id.png",
  logo: "https://llmslim.app/llmslim_logo.png",
  favicon: "https://llmslim.app/favicon.png",
  title: "LLMSlim — Hybrid Prompt Compression & Semantic Optimization Engine for LLMs",
  description:
    "Open-source Python & TypeScript library cutting LLM token costs by 40–70% in 1 line of code. Extractive, generative rewrite, and hybrid prompt compression with guaranteed 100% instruction fidelity.",
  author: "Yashvardhan Thanvi",
  creator: "Yashvardhan Thanvi",
  publisher: "LLMSlim Core Team",
  category: "Developer Tools & AI Infrastructure",
  version: "0.3.0",
  github: "https://github.com/Thanatos9404/llmslim",
  pypi: "https://pypi.org/project/llmslim/",
  license: "https://opensource.org/licenses/MIT",
  keywords: [
    "prompt compression",
    "LLM prompt optimization",
    "semantic prompt compression",
    "hybrid prompt compression",
    "reduce LLM token cost",
    "AI prompt optimization",
    "context optimization",
    "prompt optimization library",
    "RAG context compression",
    "LLM context window optimization",
    "OpenAI token saver",
    "Claude prompt optimizer",
    "Python AI infrastructure",
    "TF-IDF context compressor",
    "LexRank sentence scoring",
    "enterprise LLM cost reduction",
  ],
  googleSiteVerification: "google372537cef67c55b3",
};
